#!/usr/bin/env bash
set -eo pipefail

# latest stable NGINX 1.4.x with websocket support
add-apt-repository -y ppa:nginx/stable
apt-get update
apt-get install -y nginx dnsutils

cat<<EOF > /etc/init/nginx-reloader.conf
description     "Dokku nginx reloader service"

start on runlevel [2345]
stop on runlevel [!2345]

script
  [[ -f /home/dokku/reload-nginx ]] && rm -rf /home/dokku/reload-nginx
  echo | sudo -u git nc -l -U /home/dokku/reload-nginx && /etc/init.d/nginx reload
end script
respawn
EOF

echo "include /home/dokku/*/nginx.conf;" > /etc/nginx/conf.d/dokku.conf

sed -i 's/# server_names_hash_bucket_size/server_names_hash_bucket_size/' /etc/nginx/nginx.conf

[[ $(dig +short $HOSTNAME) ]] && echo $HOSTNAME > /home/dokku/VHOST

/etc/init.d/nginx start
start nginx-reloader || true
